#docker-compose.yml (Development)
version: "3.8"
services:
  joomlatools-server:
    image: joomlatools-server
    hostname: joomlatools-server
    container_name: joomlatools-server
    environment:
      - APP_NAME=joomlatools-server
      - APP_ENV=development
      - APP_PRELOAD=off
      - APP_DEBUG=on
      - APP_CACHE=off
      - APP_HTTP=8080
      - APP_HTTPS=8443
    restart: always
    build:
      context: .
      args:
        IMAGE_TAG: latest
        # Uncomment to deploy from Git
        #  GIT_DEPLOY_URL:
        #  GIT_DEPLOY_BRANCH: master
    # Uncomment to override environment defaults
    #env_file:
    #  - .env
    volumes:
      - ./volume:/mnt/www
      - ./:/var/www

      # Include any of the following for local development
      #- ./vendor:/tmp/www/vendor
      #- ~/Projects/joomlatools-framework:/srv/www/vendor/joomlatools/framework
      #- ~/Projects/joomlatools-pages:/srv/www/vendor/joomlatools/pages

    ports:
      - "8080:8080"  # HTTP Apache
      - "8443:8443"  # HTTPS Apache
      - "8081:8081"  # HTTP Swoole - FastCGI
      - "8082:8082"  # HTTP Swoole - API
      - "8083:8083"  # HTTP Swoole - File
      - "3306:3306"    # MySQL
      - "33060:33060"  # MySQL - X Plugin
    extra_hosts:
      - "host.docker.internal:host-gateway"