#docker-compose.yml (Development)

version: "3.8"
services:
  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
       - "1025:1025" # smtp server
       - "8025:8025" # http server